"""
Swift 1.5 27b: Swift Qwen just got faster
Starter automation script generated by Musfira AI.
Replace the placeholder logic below with your implementation.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"


def query_local_llm(prompt: str, model: str = "llama3") -> str:
    resp = requests.post(
        OLLAMA_URL,
        json={"model": model, "prompt": prompt, "stream": False},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json().get("response", "")


def main() -> None:
    prompt = "Summarize the latest update on: Swift 1.5 27b: Swift Qwen just got faster"
    print(query_local_llm(prompt))


if __name__ == "__main__":
    main()
